trigger:
  branches:
    include:
      - main

variables:
  acrName: WatchTowerACR
  tag: $(Build.BuildId)

stages:
  - stage: BuildAndPushImages
    displayName: Build and Push Docker Images
    jobs:
      - job: DockerBuildPush
        displayName: Build and Push Services
        strategy:
          matrix:
            user-service:
              repository: user-service
              dockerfilePath: ./UserService/Dockerfile
              buildContext: .
            mlnet-service:
              repository: mlnet-service
              dockerfilePath: ./MlNetService/Dockerfile
              buildContext: .

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acrName)


          - task: Docker@2
            displayName: Build & Push $(repository)
            inputs:
              command: buildAndPush
              repository: $(acrName)/$(repository)
              dockerfile: $(dockerfilePath)
              buildContext: $(buildContext)
              tags: |
                $(tag)
                latest
                
  - stage: Deploy
    displayName: Deploy to ACI
    dependsOn: BuildAndPushImages
    jobs:
      - job: DeployACI
        displayName: Deploy Multi-Container ACI
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'WatchTower-ARM'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az container delete \
                  --name watchtower-aci \
                  --resource-group rg-gs-watchTower \
                  --yes
    
                az container create \
                  --resource-group rg-gs-watchTower \
                  --name watchtower-aci \
                  --image $(acrName).azurecr.io/user-service:$(tag) \
                  --image $(acrName).azurecr.io/mlnet-service:$(tag) \
                  --registry-login-server $(acrName).azurecr.io \
                  --registry-username $(ACR_USERNAME) \
                  --registry-password $(ACR_PASSWORD) \
                  --ports 5000 5051 9090 \
                  --dns-name-label watchtower-aci-$(Build.BuildId)
                  --os-type Linux