trigger:
  branches:
    include:
      - main

variables:
  acrName: WatchTowerACR
  tag: $(Build.BuildId)

stages:
  - stage: BuildAndPushImages
    displayName: Build and Push Docker Images
    jobs:
      - job: DockerBuildPush
        displayName: Build and Push Services
        strategy:
          matrix:
            user-service:
              repository: user-service
              dockerfilePath: ./UserService/Dockerfile
              buildContext: .
            mlnet-service:
              repository: mlnet-service
              dockerfilePath: ./MlNetService/Dockerfile
              buildContext: .

        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - checkout: self

          - task: Docker@2
            displayName: Login to ACR
            inputs:
              command: login
              containerRegistry: $(acrName)


          - task: Docker@2
            displayName: Build & Push $(repository)
            inputs:
              command: buildAndPush
              repository: $(acrName)/$(repository)
              dockerfile: $(dockerfilePath)
              buildContext: $(buildContext)
              tags: |
                $(tag)
                latest
                
  - stage: Deploy
    displayName: Deploy to ACI
    dependsOn: BuildAndPushImages
    jobs:
      - job: DeployACI
        displayName: Deploy Multi-Container ACI
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'WatchTower-ARM'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az container delete \
                  --name watchtower-aci \
                  --resource-group rg-gs-watchTower \
                  --yes

                # Substitui variáveis no aci.yml
                sed -i 's|<ACR_NAME>|$(acrName)|g' aci.yml
                sed -i 's|<TAG>|$(tag)|g' aci.yml
                sed -i 's|<ACR_USERNAME>|$(ACR_USERNAME)|g' aci.yml
                sed -i 's|<ACR_PASSWORD>|$(ACR_PASSWORD)|g' aci.yml
                sed -i 's|<BUILD_ID>|$(Build.BuildId)|g' aci.yml

                az container create \
                  --resource-group rg-gs-watchTower \
                  --file aci.yml