services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - app_net 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    
  api-gateway:
    build:
        context: .
        dockerfile: ./ApiGateWay/Dockerfile
    ports:
      - 5000:8080
    depends_on:
     - user-service 
    networks:
      - app_net

  user-service:
    build:
        context: .
        dockerfile: ./UserService/Dockerfile
    ports:
     - 8080:8080
    networks:
      - app_net
  
networks:
  app_net:
    driver: bridge

volumes:
  rabbitmq_data:
    driver: local